// src/lib/types/index.ts
// Central type exports

// Database types
export type {
  JournalEntry,
  NewJournalEntry,
  InvoiceRecord,
  NewInvoice,
  EstimateRecord,
  NewEstimate,
  AccountRecord,
  DebtorRecord,
  NewDebtor,
  CreditorRecord,
  NewCreditor,
  EmailAccountRecord,
  TaxRateRecord,
  CompanyCodeRecord,
  StammdatenRecord,
  QueryResult,
  PaginationParams,
  JournalFilter,
  SortParams,
  TransactionContext
} from './database.js';

// Booking types
export type {
  SplitPosition,
  SplitGroup,
  SplitType,
  SplitMode,
  SplitValidationError,
  SplitValidationResult,
  OpenItem,
  MatchedGroup,
  MatchingError,
  MatchingResult,
  MatchingOptions,
  TaxDetails,
  TaxRate,
  BookingValidationError,
  BookingValidationResult,
  ValidationResult,
  BookingRow,
  AccountRule,
  AccountSource,
  AccountBalance,
  CalculationRow,
  StornoBooking,
  BookingPeriod,
  BookCircle,
  ContraAccountSuggestion,
  BookingTemplate,
  BatchBooking,
  NewBookingEntry,
  BookingImport,
  DuplicateCheckResult
} from './booking.js';

// API types
export type {
  ApiResponse,
  ApiError,
  ApiResponseMeta,
  PaginationMeta,
  PaginatedRequest,
  SortedRequest,
  FilteredRequest,
  DataRequest,
  JournalQueryRequest,
  JournalQueryResponse,
  JournalEntryDto,
  JournalSummary,
  CreateBookingRequest,
  UpdateBookingRequest,
  DeleteBookingRequest,
  CreateSplitBookingRequest,
  SplitPositionDto,
  CreateMatchingRequest,
  UnmatchItemsRequest,
  AccountQueryRequest,
  AccountQueryResponse,
  AccountDto,
  InvoiceQueryRequest,
  InvoiceQueryResponse,
  InvoiceDto,
  CreateInvoiceRequest,
  InvoicePositionDto,
  BookInvoiceRequest,
  UploadPdfRequest,
  ExportRequest,
  ExportResponse,
  ImportRequest,
  ImportOptions,
  ImportResponse,
  ImportError,
  BatchOperationRequest,
  BatchOperation,
  BatchOperationResponse,
  BatchOperationResult,
  HealthCheckResponse,
  HealthStatus
} from './api.js';

// UI types
export type {
  ViewMode,
  SortState,
  TableColumn,
  FilterState,
  FilterOperator,
  SelectionState,
  PaginationState,
  FormField,
  FormFieldType,
  FormFieldOption,
  FormFieldValidation,
  FormState,
  ModalState,
  DialogOptions,
  ToastMessage,
  LoadingState,
  ErrorState,
  BookingFormData,
  SplitBookingFormData,
  SplitPositionFormData,
  InvoiceFormData,
  InvoicePositionFormData,
  SearchState,
  BreadcrumbItem,
  NavigationItem,
  TabItem,
  DropdownItem,
  ActionButton,
  ToolbarState,
  SidebarState,
  ThemeConfig,
  UserPreferences,
  KeyboardShortcut,
  ContextMenuItem,
  Notification,
  FileUploadState,
  DragDropState,
  UndoRedoState,
  ExportOptions,
  PrintOptions,
  ChartDataPoint,
  ChartConfig
} from './ui.js';
